spring:
  application:
    name: accountmanager-system-service
  profiles:
    active: dev
  devtools:
    restart:
      enabled: false
mybatis:
  type-aliases-package: com.sly.demo.thymeleaf.**.model

--- 
#开发配置
spring:
  profiles: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.14.142.209:3306/accountmanager?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
server:
  port: 8081
